baseURL = "https://trainyao.github.io/"
languageCode = "zh-cn"
title = "trainyao.github.io"
theme = "hugo-theme-nix"
[params]
Name = "Hello, I'm trainyao."
HeaderUsername = "trainyao"

HeaderHostname = "home"
About = "And welcome to my blog. You can also contact me on Wechat (the_amazing_train)."
ProfilePicture = ""
GithubID = "trainyao"
LinkedInID = "昌宇-姚-618417121"
Email = "trainyao@gmail.com"

[menu]
  [[menu.header]]
    identifier = "all"
    name = "all"
    url = "/post/"
    weight = 1
  [[menu.header]]
    identifier = "category"
    name = "category"
    weight = 2


  [[menu.header]]
    parent = "category"
    name = "kubernetes"
    url = "/categories/kubernetes/"
    weight = 1
  [[menu.header]]
    parent = "category"
    name = "devops"
    url = "/categories/devops/"
    weight = 2
  [[menu.header]]
    parent = "category"
    name = "service mesh/istio"
    url = "/categories/istio/"
    weight = 2
  [[menu.header]]
    parent = "category"
    name = "service mesh/envoy/gloo"
    url = "/categories/gloo/"
    weight = 3
  [[menu.header]]
    parent = "category"
    name = "service mesh/mosn"
    url = "/categories/mosn/"
    weight = 3
  [[menu.header]]
    parent = "category"
    name = "skynet"
    url = "/categories/skynet/"
    weight = 4

  [[menu.header]]
    parent = "category"
    identifier = "translate"
    name = "翻译"
    url = "/categories/翻译/"
  [[menu.header]]
    parent = "category"
    identifier = "computer_sysem"
    name = "读书笔记/深入理解计算机系统"
    url = "/categories/深入理解计算机系统/"
  [[menu.header]]
    parent = "category"
    identifier = "kubernetes_the_definitive_guide"
    name = "读书笔记/Kubernetes 权威指南"
    url = "/categories/Kubernetes 权威指南/"
  [[menu.header]]
    identifier = "develop"
    parent = "other"
    name = "快速开发"
    url = "/categories/other/repid_develop/"

  [[menu.header]]
    identifier = "thoughts"
    parent = "category"
    name = "脑洞"
    url = "/categories/脑洞/"
    weight = 998
  [[menu.header]]
    identifier = "other"
    parent = "category"
    name = "其他"
    url = "/categories/其他/"
    weight = 999
